### ISSUE TITLE
GitHub同步功能应该支持目录结构

### ISSUE THREAD

**Issue by seekstar** [cnblogs/suggestions#13]
目前GitHub同步功能似乎只支持同步指定文件夹下面的`.md`文件，不支持同步子目录下面的`.md`文件。原因可能是大部分hexo博客都是直接将博文文件放在`source/_posts`下面。但是随着博客数量的增加，将所有文件全部直接放在同一个目录下面的话，目录会变得过于臃肿，找一个博文的`.md`文件将如同大海捞针。将博文分类并放进相应的子文件夹有助于高效管理博文，例如我的博客：<https://github.com/seekstar/blog/tree/master/source/_posts>，当我需要找到`C++内存占用分析.md`并向里面添加内容时，我只需要找到`C++`文件夹，再在里面找到`C++内存占用分析.md`这个文件即可。我相信不仅是hexo博客，大多数人用markdown记笔记也会将其分门别类以供今后查询和补充（其实我就是把hexo博客当笔记用的）。因此，我认为GitHub同步功能有必要支持目录结构。

此外，我觉得GitHub同步功能是个很重要的功能，因为github pages博客最大的问题之一就是国内的搜索引擎搜不到，我从csdn迁移到github pages之后阅读量从[六十多万](https://blog.csdn.net/qq_41961459)下降到了[两万](https://seekstar.github.io/)（所以写博客的心态也从造福人类变成了记笔记，笑）。同步到国内的博客平台相当于解决了这个痛点。因此我觉得可以考虑适当加大这个功能的推广力度，至少在会员权益那里不应该用`GitHub同步功能`描述，因为`GitHub同步功能`是有歧义的，比如`GitHub同步功能`也可能被理解为Github repository同步功能，类似于gitee上的镜像。

**Comment by cnblogs-team** [comment]
您好，收到您的建议，我们会进一步考虑

**Comment by seekstar** [comment]
现在好像新建的博客会同步到博客园了，好评。希望以后能把以前的博客也同步过去。
买终身VIP了，活下去

Update: 博客园工作人员帮我解决了，好评
