### ISSUE TITLE
关键词判断的时候能不能不要那么粗劣

### ISSUE THREAD

**Issue by liuhuo23** [cnblogs/suggestions#20]
看内容的时候请不要通过单个汉字来看

**Comment by cnblogs-team** [comment]
您好，麻烦您提供一下出现错误的相关截图和您的博客地址，我们这边确认一下

**Comment by liuhuo23** [comment]
你随便注册一个账号，账号昵称输入学习是乐趣， 然后就会报异常说是含有敏感词。 我把是乐趣删掉，还是说有敏感词， 然后我删掉学习的习，然后没有警告了。 可以正常注册了。

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，已针对这个问题进行了改进
