### ISSUE TITLE
添加邮箱，点击发送， 出现500错误

### ISSUE THREAD

**Issue by liuhuo23** [cnblogs/suggestions#21]
[image](https://github.com/cnblogs/suggestions/assets/45648682/d6803d73-d5cb-4b8d-9c0f-a7ff85151d15)

**Comment by liuhuo23** [comment]
![image](https://github.com/cnblogs/suggestions/assets/45648682/85cda130-6dd6-4511-b35c-a9347794d28d)

**Comment by cnblogs-team** [comment]
您好，我们会尽快排查这个问题，麻烦您先发邮件至 contact@cnblogs.com ，我们帮您绑定一下邮箱

**Comment by cnblogs-team** [comment]
您好，该问题已修复
